In [1]:
import pandas as pd

books = pd.read_csv("books_with_categories.csv")

In [2]:
from transformers import pipeline

classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device = 0)
classifier("I love this!")

C:\Users\bahut\PycharmProjects\book-recommender\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\bahut\PycharmProjects\book-recommender\.venv\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\bahut\.cache\huggingface\hub\models--j-hartmann--emotion-english-distilroberta-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.00852868054062128},
  {'label': 'neutral', 'score': 0.005764597095549107},
  {'label': 'anger', 'score': 0.004419781267642975},
  {'label': 'sadness', 'score': 0.002092391485348344},
  {'label': 'disgust', 'score': 0.001611992483958602},
  {'label': 'fear', 'score': 0.00041385178337804973}]]

In [3]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [4]:
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.6548415422439575},
  {'label': 'neutral', 'score': 0.16985198855400085},
  {'label': 'sadness', 'score': 0.11640863120555878},
  {'label': 'surprise', 'score': 0.02070065215229988},
  {'label': 'disgust', 'score': 0.019100679084658623},
  {'label': 'joy', 'score': 0.01516134012490511},
  {'label': 'anger', 'score': 0.003935142420232296}]]

In [5]:
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.7296029925346375},
  {'label': 'neutral', 'score': 0.1403854787349701},
  {'label': 'fear', 'score': 0.06816218793392181},
  {'label': 'joy', 'score': 0.04794237017631531},
  {'label': 'anger', 'score': 0.009156351909041405},
  {'label': 'disgust', 'score': 0.0026284761261194944},
  {'label': 'sadness', 'score': 0.0021221598144620657}],
 [{'label': 'neutral', 'score': 0.4493706226348877},
  {'label': 'disgust', 'score': 0.2735916078090668},
  {'label': 'joy', 'score': 0.10908307135105133},
  {'label': 'sadness', 'score': 0.09362722188234329},
  {'label': 'anger', 'score': 0.040478311479091644},
  {'label': 'surprise', 'score': 0.026970157399773598},
  {'label': 'fear', 'score': 0.006879046093672514}],
 [{'label': 'neutral', 'score': 0.6462162137031555},
  {'label': 'sadness', 'score': 0.2427331507205963},
  {'label': 'disgust', 'score': 0.04342265799641609},
  {'label': 'surprise', 'score': 0.028300559148192406},
  {'label': 'joy', 'score': 0.014211456291377544},
  {'label': 'fear', 'score': 0.014084109105169773},
  {'label': 'anger', 'score': 0.011031889356672764}],
 [{'label': 'fear', 'score': 0.9281681180000305},
  {'label': 'anger', 'score': 0.03219091519713402},
  {'label': 'neutral', 'score': 0.012808705680072308},
  {'label': 'sadness', 'score': 0.008756869472563267},
  {'label': 'surprise', 'score': 0.008597927168011665},
  {'label': 'disgust', 'score': 0.008431834168732166},
  {'label': 'joy', 'score': 0.0010455826995894313}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104157850146294},
  {'label': 'disgust', 'score': 0.006480592768639326},
  {'label': 'fear', 'score': 0.005393994972109795},
  {'label': 'surprise', 'score': 0.0022869452368468046},
  {'label': 'anger', 'score': 0.001842890284024179},
  {'label': 'joy', 'score': 0.0017338789766654372}],
 [{'label': 'joy', 'score': 0.9327976107597351},
  {'label': 'disgust', 'score': 0.037717510014772415},
  {'label': 'neutral', 'score': 0.015891902148723602},
  {'label': 'sadness', 'score': 0.0064445240423083305},
  {'label': 'anger', 'score': 0.005025001708418131},
  {'label': 'surprise', 'score': 0.0015812071505934},
  {'label': 'fear', 'score': 0.0005423084367066622}],
 [{'label': 'joy', 'score': 0.652870237827301},
  {'label': 'neutral', 'score': 0.2542751431465149},
  {'label': 'surprise', 'score': 0.06808307766914368},
  {'label': 'sadness', 'score': 0.00990899559110403},
  {'label': 'disgust', 'score': 0.006512210238724947},
  {'label': 'anger', 'score': 0.004821309354156256},
  {'label': 'fear', 'score': 0.0035290205851197243}],
 [{'label': 'neutral', 'score': 0.549476683139801},
  {'label': 'sadness', 'score': 0.11169018596410751},
  {'label': 'disgust', 'score': 0.10400666296482086},
  {'label': 'surprise', 'score': 0.07876557111740112},
  {'label': 'anger', 'score': 0.0641336515545845},
  {'label': 'fear', 'score': 0.05136283487081528},
  {'label': 'joy', 'score': 0.04056444391608238}]]

In [6]:
sentences = books["description"][0].split(".")
prediction = classifier(sentences)

In [7]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [8]:
prediction[0]

[{'label': 'surprise', 'score': 0.7296029925346375},
 {'label': 'neutral', 'score': 0.1403854787349701},
 {'label': 'fear', 'score': 0.06816218793392181},
 {'label': 'joy', 'score': 0.04794237017631531},
 {'label': 'anger', 'score': 0.009156351909041405},
 {'label': 'disgust', 'score': 0.0026284761261194944},
 {'label': 'sadness', 'score': 0.0021221598144620657}]

In [9]:
prediction[3]

[{'label': 'fear', 'score': 0.9281681180000305},
 {'label': 'anger', 'score': 0.03219091519713402},
 {'label': 'neutral', 'score': 0.012808705680072308},
 {'label': 'sadness', 'score': 0.008756869472563267},
 {'label': 'surprise', 'score': 0.008597927168011665},
 {'label': 'disgust', 'score': 0.008431834168732166},
 {'label': 'joy', 'score': 0.0010455826995894313}]

In [10]:
sorted(prediction[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.009156351909041405},
 {'label': 'disgust', 'score': 0.0026284761261194944},
 {'label': 'fear', 'score': 0.06816218793392181},
 {'label': 'joy', 'score': 0.04794237017631531},
 {'label': 'neutral', 'score': 0.1403854787349701},
 {'label': 'sadness', 'score': 0.0021221598144620657},
 {'label': 'surprise', 'score': 0.7296029925346375}]

In [11]:
import numpy as np

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [12]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [13]:
emotion_scores

{'anger': [0.0641336515545845,
  0.6126189827919006,
  0.0641336515545845,
  0.3514835238456726,
  0.08141248673200607,
  0.23222441971302032,
  0.5381845831871033,
  0.0641336515545845,
  0.3006700277328491,
  0.0641336515545845],
 'disgust': [0.2735916078090668,
  0.3482845723628998,
  0.10400666296482086,
  0.1507224291563034,
  0.18449552357196808,
  0.7271751761436462,
  0.15585501492023468,
  0.10400666296482086,
  0.279481440782547,
  0.17792631685733795],
 'fear': [0.9281681180000305,
  0.942527711391449,
  0.9723208546638489,
  0.36070698499679565,
  0.0950433760881424,
  0.05136283487081528,
  0.7474284768104553,
  0.40449562668800354,
  0.9155242443084717,
  0.05136283487081528],
 'joy': [0.9327976107597351,
  0.7044214010238647,
  0.7672373056411743,
  0.2518808841705322,
  0.04056444391608238,
  0.0433758981525898,
  0.8725654482841492,
  0.04056444391608238,
  0.04056444391608238,
  0.04056444391608238],
 'sadness': [0.6462162137031555,
  0.887939453125,
  0.549476683139801,
  0.732685923576355,
  0.8843895196914673,
  0.6213924288749695,
  0.7121943235397339,
  0.549476683139801,
  0.8402894735336304,
  0.8603722453117371],
 'surprise': [0.9671575427055359,
  0.11169018596410751,
  0.11169018596410751,
  0.11169018596410751,
  0.4758804440498352,
  0.11169018596410751,
  0.40799954533576965,
  0.8202828168869019,
  0.3544600009918213,
  0.11169018596410751],
 'neutral': [0.7296029925346375,
  0.2525453269481659,
  0.07876557111740112,
  0.07876557111740112,
  0.07876557111740112,
  0.27190303802490234,
  0.07876557111740112,
  0.23448754847049713,
  0.13561415672302246,
  0.07876557111740112]}

In [14]:
from tqdm import tqdm

emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5197/5197 [06:57<00:00, 12.45it/s]

In [15]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [16]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273592,0.928168,0.932798,0.646216,0.967158,0.729603,9780002005883
1,0.612619,0.348285,0.942528,0.704421,0.887939,0.111690,0.252545,9780002261982
2,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078766,9780006178736
3,0.351484,0.150722,0.360707,0.251881,0.732686,0.111690,0.078766,9780006280897
4,0.081412,0.184496,0.095043,0.040564,0.884390,0.475880,0.078766,9780006280934
...,...,...,...,...,...,...,...,...
5192,0.148208,0.030643,0.919165,0.255171,0.853722,0.980877,0.030656,9788172235222
5193,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227765,9788173031014
5194,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625,9788179921623
5195,0.064134,0.104007,0.459268,0.759456,0.951104,0.368111,0.078766,9788185300535
5196,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766,9789027712059

In [17]:
books = pd.merge(books, emotions_df, on = "isbn13")

In [18]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273592,0.928168,0.932798,0.646216,0.967158,0.729603
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612619,0.348285,0.942528,0.704421,0.887939,0.111690,0.252545
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction,0.064134,0.104007,0.972321,0.767237,0.549477,0.111690,0.078766
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction,0.351484,0.150722,0.360707,0.251881,0.732686,0.111690,0.078766
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction,0.081412,0.184496,0.095043,0.040564,0.884390,0.475880,0.078766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,...,Mistaken Identity,9788172235222 On A Train Journey Home To North...,Fiction,0.148208,0.030643,0.919165,0.255171,0.853722,0.980877,0.030656
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,Journey to the East,9788173031014 This book tells the tale of a ma...,Nonfiction,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227765
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction,0.009997,0.009929,0.339218,0.947779,0.375755,0.066685,0.057625
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction,0.064134,0.104007,0.459268,0.759456,0.951104,0.368111,0.078766
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078766

In [19]:
books.to_csv("books_with_emotions.csv", index = False)