In [2]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_chroma import Chroma
import os

In [3]:
import pandas as pd

books = pd.read_csv('books_cleaned.csv')

In [4]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [5]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: object

In [6]:
books["tagged_description"].to_csv("tagged_description.txt", index=False, header=False)

In [7]:
from langchain_core.documents import Document

documents = []
with open("tagged_description.txt", "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:
            documents.append(Document(page_content=line))

In [8]:
documents[0]

Document(page_content='"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."')

In [9]:
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

db_books = Chroma.from_documents(
    documents,
    embedding=embeddings,
    persist_directory="./db_books"
)

C:\Users\bahut\AppData\Local\Temp\ipykernel_25640\2824298087.py:1: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 0.3.0. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFaceEmbeddings`.
  embeddings = HuggingFaceEmbeddings(
C:\Users\bahut\PycharmProjects\book-recommender\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\bahut\PycharmProjects\book-recommender\.venv\lib\site-packages\huggingface_hub\file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [10]:
query = "A book to teach children about nature"

docs = db_books.similarity_search(query, k=10)
docs

[Document(page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."'),
 Document(page_content='"9780786808380 Introduce your babies to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing the baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(page_content='"9780786808397 Introduce your baby to birds, cats, dogs, and babies through fine art, illustration, and photographs. These books are a rare opportunity to exopse little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information about the subjects."'),
 Document(page_content='"9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child\'s drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects."'),
 Document(page_content='"9780060959036 Barbara Kingsolver\'s fifth novel is a hymn to wildness that celebrates the prodigal spirit of human nature, and of nature itself. It weaves together three stories of human love within a larger tapestry of lives amid the mountains and farms of southern Appalachia. Over the course of one humid summer, this novel\'s intriguing protagonists face disparate predicaments but find connections to one another and to the flora and fauna with which they necessarily share a place."'),
 Document(page_content='"9780786819119 Charming illustrations and playful rhythmic verse make real-life learning fun by taking babies and toddlers on an adventurous discovery of water and its many sources. Squeezable and floatable, Water, Water, Everywhere can be enjoyed in and out of the tub."'),
 Document(page_content='"9780064402453 ‘Racso, a brash and boastful little rodent, is making his way to Thorn Valley, determined to learn how to read and write and become a hero. His bragging and lies get him off to a bad start, but a crisis gives him the opportunity to prove his mettle. A worthy successor [to Mrs. Frisby and the Rats of NIMH, a Newbery Medal winner by the author\'s father].\' \'BL. 1986 Children\'s Editors\' Choices (BL) Children\'s Choices for 1987 (IRA/CBC) Notable 1986 Childrens\' Trade Books in Social Studies (NCSS/CBC) 1986 Children\'s Books (NY Public Library) Best Science Fiction/Fantasy 1986 (VOYA)"'),
 Document(page_content='"9780064403870 When Margaret and her younger brother, Artie, get lost in the woods on a family camping trip, they are rescued by rats -- the superintelligent rats of NIMH. Taken into the rat\'s community, the children are safe for the time being. But winter is coming. Margaret and Artie have to get back home. And when they do, they must protect the rats who have helped them. Everything depends on their silence... but it\'s hard to evade questions forever. Children\'s Choices for 1991 (IRA/CBC)VOYA\'s Best Science Fiction, Fantasy, and Horror 1990Parenting Honorable Mention, Reading Magic Award"'),
 Document(page_content='"9780802431486 Drawn from years of counseling and the author\'s own parenting experiences, this valuable resource, filled with Scripture passages and accompanying practical applications, provides principles for raising and nurturing children in these uncertain and rapidly changing times. Original."'),
 Document(page_content='"9781593851170 ""Comprehensive and up to date, this tightly edited volume belongs on the desks of researchers and students in developmental psychology, comparative psychology, animal behavior, and evolutionary psychology, and will also be of interest to anthropologists. It is a richly informative text for advanced undergraduate- and graduate-level courses.""--BOOK JACKET."')]

In [11]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip().replace('"', ""))]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3747,9780786808069,0786808063,Baby Einstein: Neighborhood Animals,Marilyn Singer;Julie Aigner-Clark,Juvenile Fiction,http://books.google.com/books/content?id=X9a4P...,Children will discover the exciting world of t...,2001.0,3.89,16.0,180.0,Baby Einstein: Neighborhood Animals,9780786808069 Children will discover the excit...

In [12]:
def retrieve_semantic_recommendations(query: str, top_k=10)->pd.DataFrame:
    recs = db_books.similarity_search(query, k=50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [13]:
retrieve_semantic_recommendations("Death by drowning")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
38,9780007120680,0007120680,Hallowe'en Party,Agatha Christie,"Poirot, Hercule (Fictitious character)",http://books.google.com/books/content?id=Qlx98...,No one believes a little girl when she insists...,2001.0,3.66,336.0,18820.0,Hallowe'en Party,9780007120680 No one believes a little girl wh...
158,9780060577049,0060577045,Slouching Toward Nirvana,Charles Bukowski,Poetry,http://books.google.com/books/content?id=L_7nl...,"in this place there are the dead, the deadly a...",2006.0,3.99,288.0,1901.0,Slouching Toward Nirvana: New Poems,9780060577049 in this place there are the dead...
232,9780060788384,0060788380,For a Few Demons More,Kim Harrison,Fiction,http://books.google.com/books/content?id=ya3Nq...,When a serial murderer begins killing off memb...,2007.0,4.33,456.0,47314.0,For a Few Demons More,9780060788384 When a serial murderer begins ki...
451,9780072920963,0072920963,The Last Dance,Lynne Ann DeSpelder;Albert Lee Strickland,Social Science,http://books.google.com/books/content?id=CAlHA...,"The best-selling textbook in the field, The La...",2005.0,3.77,664.0,112.0,The Last Dance: Encountering Death and Dying,9780072920963 The best-selling textbook in the...
521,9780099481249,0099481243,Enduring Love,Ian McEwan,Accidents,http://books.google.com/books/content?id=S702H...,"""The story of how an ordinary man can be drive...",2004.0,3.63,245.0,29552.0,Enduring Love,"9780099481249 ""The story of how an ordinary ma..."
723,9780141007458,0141007451,Stiff,Mary Roach,Dead,http://books.google.com/books/content?id=X157P...,What happens to your body after you have died?...,2004.0,4.06,304.0,970.0,Stiff: The Curious Lives of Human Cadavers,9780141007458 What happens to your body after ...
938,9780156949606,0156949601,The Waves,Virginia Woolf,Experimental fiction,http://books.google.com/books/content?id=7HEM1...,"Against the background of the sea, the author ...",1959.0,4.14,297.0,19210.0,The Waves,9780156949606 Against the background of the se...
1188,9780312202057,0312202059,Requiem for Harlem,Henry Roth,Fiction,http://books.google.com/books/content?id=JDTsV...,The fourth and final volume of the epic series...,1998.0,4.16,304.0,51.0,Requiem for Harlem: Mercy of a Rude Stream Vol...,9780312202057 The fourth and final volume of t...
1194,9780312252816,0312252811,Death in the Andamans,M. M. Kaye,Fiction,http://books.google.com/books/content?id=lMFbM...,While visiting the Andaman Islands in the Indi...,2000.0,3.93,272.0,813.0,Death in the Andamans,9780312252816 While visiting the Andaman Islan...
1204,9780312277109,0312277105,An Unfortunate Woman,Richard Brautigan,Fiction,http://books.google.com/books/content?id=Fx4k5...,"Completed prior to the author's 1984 suicide, ...",2001.0,3.78,132.0,1312.0,An Unfortunate Woman: A Journey,9780312277109 Completed prior to the author's ...
1342,9780316016650,0316016659,Cirque Du Freak #10: The Lake of Souls,Darren Shan,Young Adult Fiction,NaN,"""If you step through after Harkat, you might n...",2006.0,4.19,272.0,18011.0,Cirque Du Freak #10: The Lake of Souls: Book 1...,"9780316016650 ""If you step through after Harka..."
1516,9780345457691,0345457692,Altered Carbon,Richard K. Morgan,Fiction,http://books.google.com/books/content?id=xXp3M...,In a twenty-fifth-century world in which death...,2006.0,4.06,526.0,52810.0,Altered Carbon,9780345457691 In a twenty-fifth-century world ...
1580,9780349100470,0349100470,The Drowned and the Saved,Primo Levi,Auschwitz (Poland : Concentration camp),http://books.google.com/books/content?id=U35BP...,Shortly after completing THE DROWNED AND THE S...,1989.0,4.39,170.0,3319.0,The Drowned and the Saved,9780349100470 Shortly after completing THE DRO...
1669,9780375507151,0375507159,Cliffs of Despair,Tom Hunt,Psychology,http://books.google.com/books/content?id=Tb32w...,Interweaving personal reminiscences and invest...,2006.0,3.72,256.0,70.0,Cliffs of Despair: A Journey to the Edge,9780375507151 Interweaving personal reminiscen...
1675,9780375701474,0375701478,Night Falls Fast,Kay Redfield Jamison,NaN,http://books.google.com/books/content?id=NTeOD...,A study of the growing epidemic of suicide amo...,2011.0,4.09,432.0,5211.0,Night Falls Fast,9780375701474 A study of the growing epidemic ...
1718,9780375727276,0375727272,Lunar Park,Bret Easton Ellis,Fiction,http://books.google.com/books/content?id=gfNuo...,Becoming a best-selling novelist and wealthy c...,2006.0,3.62,404.0,19185.0,Lunar Park,9780375727276 Becoming a best-selling novelist...
1796,9780385129916,0385129912,Night Shift,Stephen King,Fiction,http://books.google.com/books/content?id=sl3DF...,More than twenty-five stories of horror and ni...,1978.0,3.99,344.0,470.0,Night Shift,9780385129916 More than twenty-five stories of...
1816,9780385333870,0385333870,Galapagos: A Novel,Kurt Vonnegut,Fiction,http://books.google.com/books/content?id=AZjb-...,The ghost of a decapitated shipbuilder wryly o...,1999.0,3.87,324.0,53777.0,Galapagos: A Novel,9780385333870 The ghost of a decapitated shipb...
1930,9780393329124,0393329127,Spook: Science Tackles the Afterlife,Mary Roach,Language Arts & Disciplines,http://books.google.com/books/content?id=9S2yr...,"Draws on the achievements of scientists, engin...",2006.0,3.58,311.0,29027.0,Spook: Science Tackles the Afterlife,9780393329124 Draws on the achievements of sci...
2023,9780425181119,0425181111,Strangers,Dean Koontz,Fiction,http://books.google.com/books/content?id=CUAWZ...,A group of seemingly unrelated people experien...,2002.0,4.00,704.0,38003.0,Strangers,9780425181119 A group of seemingly unrelated p...
2083,9780425213384,0425213382,Cause of Death,Patricia Daniels Cornwell,Fiction,http://books.google.com/books/content?id=f8ZaP...,"The mysterious death of diver Ted Eddings, an ...",2007.0,3.93,356.0,37965.0,Cause of Death,9780425213384 The mysterious death of diver Te...
2118,9780439436564,0439436567,Drowned Wednesday,Garth Nix,Juvenile Fiction,http://books.google.com/books/content?id=vlXIz...,"Wednesday has rolled around, and Arthur Penhal...",2006.0,3.86,389.0,22909.0,Drowned Wednesday,"9780439436564 Wednesday has rolled around, and..."
2255,9780446354738,0446354732,Nothing Lasts Forever,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=_uUTS...,"Three young doctors-their hopes, their dreams,...",1995.0,3.83,384.0,25396.0,Nothing Lasts Forever,"9780446354738 Three young doctors-their hopes,..."
2314,9780446698870,0446698873,The Black Dahlia,James Ellroy,Fiction,http://books.google.com/books/content?id=R2s-P...,"On January 15, 1947, the torture-ravished body...",2006.0,3.75,348.0,68551.0,The Black Dahlia,"9780446698870 On January 15, 1947, the torture..."
2356,9780451170118,0451170113,Night Shift,Stephen King,Fiction,http://books.google.com/books/content?id=jIQL9...,Twenty stories of horror and nightmarish fanta...,1978.0,3.99,326.0,1273.0,Night Shift,9780451170118 Twenty stories of horror and nig...
2375,9780451210630,0451210638,A Case of Need,Michael Crichton,Fiction,http://books.google.com/books/content?id=nHJPP...,When a young woman dies mysteriously on an ope...,2003.0,3.70,416.0,15655.0,A Case of Need,9780451210630 When a young woman dies mysterio...
2380,9780451211576,045121157X,Monkeewrench,P. J. Tracy,Fiction,http://books.google.com/books/content?id=IHFKP...,Grace McBride and the team at her software com...,2004.0,4.12,421.0,7696.0,Monkeewrench,9780451211576 Grace McBride and the team at he...
2630,9780552152952,0552152951,Reaper Man,Terry Pratchett,Discworld (Imaginary place),http://books.google.com/books/content?id=Sosgq...,'Death has to happen. Tha'ts what bein' alive ...,2005.0,4.29,352.0,59901.0,Reaper Man,9780552152952 'Death has to happen. Tha'ts wha...
2655,9780552999953,0552999954,High Society,Ben Elton,Fiction,http://books.google.com/books/content?id=yzh0p...,The author presents a terrifying vision of a w...,2003.0,3.77,380.0,5981.0,High Society,9780552999953 The author presents a terrifying...
2765,9780553582918,0553582917,Intensity,Dean Ray Koontz,Fiction,http://books.google.com/books/content?id=9X7qX...,The sole survivor of a homicidal sociopath's l...,2000.0,4.04,436.0,62698.0,Intensity,9780553582918 The sole survivor of a homicidal...
2771,9780553584486,0553584480,The Face,Dean Ray Koontz,Fiction,http://books.google.com/books/content?id=h5nm4...,When a Hollywood star becomes the target of a ...,2003.0,3.70,649.0,18321.0,The Face,9780553584486 When a Hollywood star becomes th...
2806,9780571090242,0571090249,Death of a Naturalist,Seamus Heaney,Poetry,http://books.google.com/books/content?id=et6dA...,Death of a Naturalist marks the auspicious out...,1969.0,4.29,57.0,63.0,Death of a Naturalist: Volume one,9780571090242 Death of a Naturalist marks the ...
2850,9780582418172,0582418178,The Body,Stephen King;Robin Waterfield,Friendship in adolescence,http://books.google.com/books/content?id=Rth4Q...,"In 1960s America, four young boys go on a jour...",1999.0,4.26,80.0,27417.0,The Body,"9780582418172 In 1960s America, four young boy..."
2856,9780586210680,0586210687,The Master of Whitestorm,Janny Wurts,Fantasy fiction,http://books.google.com/books/content?id=vIaCQ...,Everyone knew that there was no escape from th...,1992.0,3.91,413.0,78.0,The Master of Whitestorm,9780586210680 Everyone knew that there was no ...
2978,9780671025700,0671025708,The Last Dance,Ed McBain,Fiction,http://books.google.com/books/content?id=OGxiK...,"In this city, you can get anything done for a ...",2000.0,3.69,336.0,727.0,The Last Dance,"9780671025700 In this city, you can get anythi..."
3053,9780676977110,0676977111,Never Let Me Go,Kazuo Ishiguro,Boarding school-fiction,http://books.google.com/books/content?id=taygT...,A gothic tour de force. A meditation on mortal...,2006.0,3.81,288.0,1091.0,Never Let Me Go,9780676977110 A gothic tour de force. A medita...
3150,9780684842233,0684842238,On Death and Dying,Elisabeth Kübler-Ross,Family & Relationships,http://books.google.com/books/content?id=zb-ZN...,Explains the attitudes of the dying toward the...,1997.0,4.16,288.0,140.0,On Death and Dying,9780684842233 Explains the attitudes of the dy...
3156,9780684846316,0684846314,The Wheel of Life,Elisabeth Kübler-Ross,Biography & Autobiography,http://books.google.com/books/content?id=wpWic...,An authority on death and dying offers a memoi...,1998.0,4.16,288.0,1035.0,The Wheel of Life: A Memoir of Living and Dying,9780684846316 An authority on death and dying ...
3370,9780743417341,0743417348,The Inhuman Condition,Clive Barker,Fiction,http://books.google.com/books/content?id=RaMMC...,"Presents five horror tales, including a bloody...",2001.0,3.97,180.0,6129.0,The Inhuman Condition,"9780743417341 Presents five horror tales, incl..."
3442,9780744578263,0744578264,The Sea-thing Child,Russell Hoban,Birds,http://books.google.com/books/content?id=CEt9O...,"Washed up on the beach during a storm, the sea...",2000.0,3.79,48.0,100.0,The Sea-thing Child,9780744578263 Washed up on the beach during a ...
3623,9780765308702,0765308703,What Dreams May Come,Richard Matheson,Fiction,http://books.google.com/books/content?id=3psmm...,The New York Times bestseller A LOVE THAT TRAN...,2004.0,3.95,288.0,8985.0,What Dreams May Come: A Novel,9780765308702 The New York Times bestseller A ...
3653,9780765344724,0765344726,Hawkes Harbor,S. E. Hinton,Fiction,http://books.google.com/books/content?id=rCYqk...,Haunted by the past he endured for his illegit...,2005.0,3.13,289.0,2084.0,Hawkes Harbor,9780765344724 Haunted by the past he endured f...
3865,9780805073669,0805073663,In Harm's Way,Doug Stanton,History,http://books.google.com/books/content?id=oBaI6...,Chronicles the worst disaster in U.S. naval hi...,2003.0,4.28,384.0,15946.0,In Harm's Way: The Sinking of the U.S.S. India...,9780805073669 Chronicles the worst disaster in...
4501,9781416524519,1416524517,Cell,Stephen King,Fiction,http://books.google.com/books/content?id=lWIsD...,Mayhem and violence are unleashed around the w...,2006.0,3.65,449.0,163786.0,Cell: A Novel,9781416524519 Mayhem and violence are unleashe...
4541,9781421509594,1421509598,The Drifting Classroom,Kazuo Umezu,Comics & Graphic Novels,http://books.google.com/books/content?id=6ME-P...,A flash flood turns the desert into a drowned ...,2007.0,3.94,192.0,311.0,The Drifting Classroom,9781421509594 A flash flood turns the desert i...
4600,9781560257011,1560257016,"Pink Flamingos, and Other Filth",John Waters,Performing Arts,http://books.google.com/books/content?id=nNlBZ...,"Here are three of the filthiest-and yet, in th...",2005.0,4.22,258.0,49.0,"Pink Flamingos, and Other Filth: Three Screenp...",9781560257011 Here are three of the filthiest-...
4619,9781563893339,1563893339,Death,Neil Gaiman;Chris Bachalo;Mark Buckingham;Mike...,Comics & Graphic Novels,http://books.google.com/books/content?id=VIdbP...,"A tale of music, mortality, friendship and dea...",1997.0,4.22,95.0,12206.0,Death: The Time of Your Life,"9781563893339 A tale of music, mortality, frie..."
5023,9781852864989,1852864982,Death,Neil Gaiman,Death (Fictitious character : Gaiman),http://books.google.com/books/content?id=5XnXO...,"A tale of music, mortality, friendship and dea...",1994.0,4.18,104.0,37678.0,Death: The High Cost of Living,"9781852864989 A tale of music, mortality, frie..."
5043,9781857233940,1857233948,Excession,Iain Banks,English fiction,http://books.google.com/books/content?id=YqpyQ...,By the author of Feersum Endjinn. The Excessio...,1996.0,4.20,451.0,165.0,Excession,9781857233940 By the author of Feersum Endjinn...
5070,9781860469015,1860469019,Baltasar & Blimunda,José Saramago,Aeronautics,http://books.google.com/books/content?id=VTUF8...,"In early eighteenth-century Lisbon, Baltasar, ...",2001.0,3.91,346.0,97.0,Baltasar & Blimunda,9781860469015 In early eighteenth-century Lisb...

In [15]:
# Inspect the content of your Chroma DB
items = db_books.get()
print("Number of vectors:", len(items["ids"]))

for i in range(len(items["documents"])):
    print(i, items["ids"][i], items["documents"][i][:150])

Number of vectors: 5197
0 000802c3-4374-4fba-977a-1c6b26c41e0d "9781563898945 Chronicles the battles of Spider Jerusalem, infamous renegade journalist of the future. Spider dedicates himself to fighting the corrup
1 0042a11c-208c-45af-bfac-1e4ea0d26084 "9780812574999 When the Demon Jupiter is provoked into hurling his dreaded Red Spot at the magical land of Xanth, it falls to Umlaut, a young man with
2 004a6280-431d-41f7-a8c3-4fec20a92606 "9780448444826 Looks closely at Anne Frank's life before the secret annex, what life was like in hiding from the Nazis, and the legacy of her diary."
3 004e879b-e0f5-4c16-9797-6fc81c37c394 "9780374527051 Presents a modern translation of the ancient Greek trilogy which traces the chain of murder and revenge within the royal family of Argo
4 00515ed1-e7c8-4034-addd-0e7d42330d85 "9780142408759 Recently inheriting his deceased dad's job as a dragon catcher/exterminator, Robert's new job creates conflicting issues for him becaus
5 0052ca5c-3738-4dbf-addb-756045d9fc24 "9780972018418 The popular fitness author explains how to achieve a healthy lifestyle and avoid dieting by planning balanced, nutritious meals and off
6 0054db26-a59c-40c0-bc59-f1ec71df3252 "9780765308702 The New York Times bestseller A LOVE THAT TRANSCENDS HEAVEN AND HELL What happens to us after we die? Chris Nielsen had no idea, until
7 00687e9b-253a-4e0e-9b67-da123c25fa6b "9780440414001 Sam Krupnik, mad at his mother because she won't let him wear his new plastic fangs in the house, decides to run away to Alaska."
8 007580f1-2328-4d6e-8b7f-605fb0c4355c "9780226735191 With this volume, the University of Chicago Press completes its translation of a work that is indispensable not only to serious readers
9 007f8546-cf67-42da-a242-ba96387446cc "9780374253844 Floria Aemilia, a concubine to St. Augustine for more than ten years prior to his spiritual awakening, challenges St. Augustine's view
10 008d99fb-62c8-4054-a7e1-d476bb9bb326 "9780553267600 For use in schools and libraries only. Once he was an orphan called Pug, apprenticed to a sorcerer of the enchanted land of Midkemia. T
11 009a41fb-97a3-4695-a2bb-7bad9eaa67ae "9780718149291 A detective novel with a series of characters to relish - Gaius Petreius Ruso and a cast of corrupt officers, cut throat villains, begu
12 00aa0c64-8349-415d-80f7-1a177d86df3e "9781569716199 Collecting the first four issues of the quarterly anthology smash sensation, Star Wars Tales contains thrilling stories featuring Darth
13 00b32f29-1a06-42f8-b4c2-f4832857de39 "9780671867423 An account of Lincoln's revolutionary speech describes how, in the space of 272 words, the President brought to bear the rhetoric of th
14 00bf8a3d-64d5-4374-951c-aa692034abf5 "9780767901574 Drawing on three decades of learning from the spiritual masters of Asia, an American lama illuminates the sacred wisdom and practices o
15 00c31b90-da6b-4904-b0d6-cd0a8d54fa09 "9780385495226 Describes how a strain of lethal virus showed up in 1989 at a Virginia laboratory, and relates the efforts of a military biohazard SWAT
16 00c41d88-cd46-4762-be2b-50ab4e0400b2 "9780312981662 In the sprawling, half-timbered mansion in the affluent suburb of Swinly Dean, Aristide Leonides lies dead from barbiturate poisoning.
17 00da8ebd-9df5-4696-b719-1d143c3a45e7 "9781563892462 /Dave McKean, illustrator In his grandfather's seaside arcade, a young boy encounters a mysterious Punch & Judy man with a dark past an
18 00e79b10-db5f-428b-bc7f-234a5b281838 "9780007136582 Since it was first published in 1954, 'The Lord of the Rings' has been a book people have treasured. Steeped in unrivalled magic and ot
19 00f541a4-eaf0-40f0-a7b5-03a05583bcac "9781582406930 Detective Richard Fell is transferred over the bridge from the big city to Snowtown, a collapsing urban trashzone. In a place where not
20 00f68e04-4182-4971-a8e5-e80b893bdabc "9780785123262 Sixteen million mutants dead... and that was just the beginning! In one bold stroke, writer Grant Morrison (The Invisibles, JLA, Fantas
21 00fb3060-047e-4ccd-99c6-0486e3043396 "9780735617223 Covers topics such as the importance of secure systems, threat modeling, canonical representation issues, solving database input, denia
22 010bab00-3db1-47d4-97d6-b52e6f3ba174 "9780312990695 Imprisoned and drugged in a restricted island psychiatric facility for government intelligence employees, former Consular Operations ag
23 011dc7e4-a0fc-428d-858c-4980f7b828a4 "9781590525937 When a university professor is found murdered, a brilliant and quick-witted homicide detective, Ollie Chandler, suspects the murderer c
24 01236be0-29e4-45bb-ae76-5bf633a9ff3e "9780425181645 Examines the science and scientists who provided the backdrop to Einstein's influential 1905 discovery and offers an explanation of the
25 012cac46-ce26-409d-bfd6-e078ecd8f821 "9780802775931 The Illustrated Longitude recounts in words and images the epic quest to solve the greatest scientific problem of the eighteenth and th
26 013685c4-578e-49cf-a14f-965b6b9ae45a "9780582418271 Mitch McDeere, a Harvard Law graduate, becomes suspicious of his Memphis tax firm when mysterious deaths, obsessive office security, an
27 016583e0-95f2-476b-8d64-31abaa6092fb "9781932855418 Drawing from the collection of the world-renowned Macaulay Library at the Cornell Lab of Ornithology, Bird Songs presents the most nota
28 01695da9-3b79-48d7-a882-51e3acecf8a1 "9781401210014 Exiled from their homelands by an evil adversary, various fairy tale and folklore characters, referred to as ""Fables"", are forced to
29 017f17f2-52d5-4f7f-9713-ba82f979e3d8 "9780939682041 The essential source book for anyone wanting to pursue the SI. A vast compendium of writings from all their major works, books, journal
30 01809457-b66f-4dd7-9795-f4f48fb00287 "9780765346520 The masterpiece that started The New York Times bestselling epic Sword of Truth In the aftermath of the brutal murder of his father, a
31 0180a440-9de7-4563-a9aa-83f833a87a87 "9780375835315 High school student Nick O'Leary, member of a rock band, meets college-bound Norah Silverberg and asks her to be his girlfriend for fiv
32 018f33ca-083d-424c-99b7-1a3b155daa76 "9780131871656 This introduction to astronomy features an exceptionally clear writing style, an emphasis on critical thinking and visualization, and a
33 0192e765-d736-4068-8032-73d3e78982ac "9780006512677 Spares - human clones, the ultimate health insurance. An eye for an eye - but some people are doing all the taking. The story of Jack R
34 01ab166c-f061-4439-8ea7-46ad8a394814 "9780099928409 Billy Twillig has won the first Nobel Prize ever to be given in mathematics. Set in the near future, this book charts an innocent's edu
35 01b185d9-1cc4-47c9-ac35-26eae12ae95d "9781577782087 Spend Today As If It Were Your Last For those who've read Jesus Freaks, this book is the next step. Focusing on life application, the b
36 01b6ab56-c233-43fe-b1bf-204be71103fe "9780590321143 Flying with her uncle in his small plane, 13-year-old Debbie who has been blind for about a year must suddenly take control of the plan
37 01ba28dd-6eb0-4e7d-a910-682f12285dba "9781557091031 Copied out by hand as a young man aspiring to the status of Gentleman, the 110 precepts which make up this work were based on a set of
38 01d0e602-8bae-4bab-9a39-21d17e278f65 "9780575075825 When Grendel is drawn up from the caves under the mere where he lives with his bloated, inarticulate hag of a mother into the fresh nig
39 01d2708c-b601-4628-a5ba-e733ec4e8ef6 "9780930588793 Miller's masterful book, based on his years during the 1850s among the mining towns and Indian camps of northern California, is an acco
40 01e80ef5-dba1-46b7-a6e3-6ad13a47de8e "9780689840333 The Dark is rising in its last and greatest bid to control the world. And Will Stanton -- last-born of the immortal Old Ones, dedicated
41 01e98ec2-511d-44aa-bc7e-2cad4281cc3c "9780131935075 This new edition is an authoritative and provides a balanced account of the history of art. It presents art history as an essential par
42 01f8a52c-c2de-4715-8994-60aafbec5c1e "9780399153594 Hoping to reconcile with the mother of his child, reluctant contract killer John Rain inadvertently places them in the path of dangerou
43 01fe395f-fece-472b-8e39-e974ce7d290a "9781565125605 Ninety-something-year-old Jacob Jankowski remembers his time in the circus as a young man during the Great Depression, and his friendsh
44 020819a9-86d4-4b9c-8f05-d7be32bea391 9780823006571 The works of Old Masters and today's most respected realist artists are used to demonstrate and teach the principles of realist drawing
45 0215d724-1436-4645-a0d3-7a67a7723962 "9780441014439 Spanning a quarter of a century, an anthology of previously uncollected short fiction explores a world of magic in such works as ""The
46 0237410b-b6c3-456a-b8bd-11c4e1162c5c 9781932382723 The notorious Belasco House starts to exert its dark influence on the group of scientists and spiritualists as they unearth the perverse
47 023bb822-5d56-4d2a-a44a-920970ac75ab 9780739447345 Amateur sleuth Alvirah Meehan and private investigator Regan Reilly join together to solve a case involving an eighty-foot blue spruce t
48 0244f0fd-154d-41ae-ad45-152197a5b9b2 "9780743470124 Having relocated to an alienating Connecticut suburb after a mugging in her native New York City, wife and mother Kate Klein undertakes
49 027409c1-a3a4-49d8-9784-9d878fa59e0d "9780684867489 The National Bestseller What is the lesson in abuse, neglect, abandonment, rejection? What is the lesson when you lose someone you real
50 027c8918-ab52-4c18-83a3-d3e7583d8e14 "9780060792787 A new evil threatens Midkemia, its web stretching from the deepest criminal underworld all the way up to the highest seats of power in
51 02913578-e1d5-49de-8fbb-844b0fc242f6 "9780385497091 A boy wracked with a serious oral fixation tries everything to break the cycle--sex, substance abuse, fly fishing, work, and religion--
52 02949c2f-a2e0-445a-9e50-e3685e0f56a2 "9781593083779 Presents the first book of Proust's monumental work ""Remembrance of Things Past"", introducing such themes as the destructive force of
53 02a105c3-9879-43ba-8bc9-2feb76b95a0a "9780618619078 Offers an account of the first great human rights crusade, which originated in England in the 1780s and resulted in the freeing of hund
54 02b26b6e-ca43-45d6-84f8-3c8b8f5611fd "9780843953244 A handsome British knight travels to Scotland eager to fulfill a marriage contract, but finds the feisty temper of his stinning bride t
55 02c3d9d4-cc08-44f0-84d7-d32a97555c91 "9780805242256 A political analysis of totalitarian societies, originally published in 1951, traces the nineteenth-century rise of anti-Semitism in ce
56 02d0ee5d-b793-40e1-a812-34a1358c09f8 "9780520215108 In this study of upper-class masculinity from the end of the ancien régime in 1789 to the end of World War I, Robert Nye argues that ma
57 02db82ba-8825-4fee-92fc-89b5447465e2 "9780143039938 A whimsical compendium of mythological creature profiles considers the inventions of such literary masters as Shakespeare, Lewis Carrol
58 02e5570c-dbc6-4b1a-a320-8fc2ca19d467 "9780231138703 Mauboussin mines disciplines that are not normally associated with finance such as biology, physics, and psychology to help investors m
59 02ec7ae6-fdb3-4edc-8046-e8aa92d22dd2 "9781580495790 This Prestwick House Literary Touchstone Edition includes a glossary and reader's notes to help the reader fully appreciate the beauty
60 02f030f4-434a-45c0-98b0-b2f82c289555 "9780060777333 From the winner of the National Book Foundations' 2000 Medal for Distinguished Contribution to American Letters comes a ""sweet, funny
61 02f05483-b29d-412a-be3e-53a7061660c4 "9781859843987 Calling upon personal testimony and documents released under the Freedom of Information Act, chronicles the life of Henry Kissinger, li
62 02fae45c-ad63-4743-bd62-ca999924d548 "9780007151240 It should be the most natural thing in the world. But in Tony Parsons' latest bestseller, three couples discover that Mother Nature can
63 02fb82af-6055-4cfa-88b6-d07ff95bae6b "9780393703351 Employing a multifaceted, flexible approach based on solution-focused therapy, the author offers clear and sensible ideas for working w
64 0307fa99-98bc-46c0-b369-ebff26d95197 "9780312877514 Lovelock is a capuchin monkey engineered to be the perfect servant--intelligent, agile, pliant, and devoted to his owner. He is a Witne
65 031131ef-784e-4fa8-ac29-f14f1fb59ad0 "9780393321630 A collection of thirteen essays from a variety of sources examines one of America's most serious domestic problems, investigates its hi
66 031aa73c-a9d6-4470-8dc8-050bc8632be5 "9780590488150 Laura and her family move to Minnesota where they live in a dugout until a new house is built and face misfortunes caused by flood, bli
67 032f6ab2-6b41-4f6b-b425-3f03b16421bd "9780786816156 A BookSense 76 pick, and best-seller from coast to coast-Summerland is part fantasy, part adventure, part baseball, but most of all it'
68 0330f2bd-9ee6-477e-b6e9-edb5ee9b8cb7 "9780375415036 Presents a collection of essays from George Orwell, including his discussion of pacifism, ""My Country Right or Left,"" his scathingly
69 0346c008-e96c-4439-b017-0af9e902a422 "9780970998712 Dean Koontz is one of the world's top-selling authors with total worldwide sales of his novels at 225 million copies! He achieves what
70 03478f2d-a2a4-4c5d-bee1-55a960c868ff "9780374530310 The Georgics is a poem by Latin poet Virgil, likely published in 29 BC. As the name suggests (from the Greek word γεωργικά, geōrgika, i
71 0350973f-bfbd-4c65-9a06-621b3b8dc6a1 9780312155322 An old Jew looks back on his climb from the slums of New York into the rarefied world of wealth and intellect. He describes a romance wi
72 03532e6a-36bf-4b2d-ae10-c5fea9877bbc "9780439933414 J.D. continues to search for answers about her past and about the dangerous powers that she cannot control, while the memories implante
73 036f9238-8ad2-46ac-8e80-e6d7ac8d527b "9780671041557 In a novel based on the popular computer game, Norrec Vizharan stumbles upon the ancient armor of Bartuc, the legendary Warlord of Bloo
74 037f8a1c-babf-494b-81c0-62cad0ea5f50 "9781904271550 This second volume gives readers the First Quarto text of 1603 and The Folio Text of 1623, fully modernised and edited to the usual Ard
75 03873764-94c2-4148-ac4c-f545033424e4 "9780345481290 British naval officer Will Laurence's partnership with Temeraire, a rare Chinese imperial dragon, is threatened when Temeraire is summo
76 0399f75d-18fc-4c1d-b69e-42f42fa69ca5 "9780394733524 A mathematically oriented romantic fable about the eternal triangle, in this case a straight line who is hopelessly in love with a dot
77 03ad0f06-4863-4f63-afe3-f1a3a64f61e3 "9780385339667 Years after the bombing of a Mississippi law office in which Marvin Kramer's two sons died, former Klan member Sam Cayhill, the accused
78 03cc1601-aa72-4aaa-8f16-ae2604169308 "9781414306346 Provides a Christian interpretation of the first six books, arguing that the series supports biblical teaching as opposed to the practi
79 03cdbaaa-e69b-4de0-aa0b-e0d4b066a6d4 "9780061120077 The beloved American classic about a young girl's coming-of-age at the turn of the century, Betty Smith's A Tree Grows in Brooklyn is a
80 03e00243-466e-47dc-ae12-e4bd773430f8 "9780425182673 When a group of terrorists who call themselves ""CyberNation,"" and consider themselves an independent virtual country, seize control o
81 03f64355-8f79-4866-8b4f-aecff68083c9 "9780349116303 The riveting memoirs of the outstanding moral and political leader of our time, LONG WALK TO FREEDOM brilliantly recreates the drama of
82 040e25a2-4a2c-44b8-8ae1-9883d416d41e "9780747264866 Love is always just around the corner in a Jill Mansell novel - with a few surprises and a lot of humour on the way to happiness When M
83 041eaa8e-d6e2-4b7e-8cf4-060fd4301232 "9780345437839 When her ""deceased"" con man husband turns up after being declared dead in a plane crash, he's threatening to blackmail Rhoda Lorton,
84 042421f2-3a86-4ebd-b03a-58e7e736f251 9780451208644 A white writer recounts his experiences in the American South following treatments that darkened his skin and shares his thoughts on the
85 042cf385-7f7f-4438-924f-393c7b68d639 "9780340829776 There are new evils, new dangers to threaten Roland's little band in the devastated city of Lud and the surrounding wastelands, as well
86 042f3462-4a08-4c4c-8197-0924584384b0 "9781586638535 Presents the original text of Shakespeare's play side by side with a modern version, with marginal notes and explanations and full desc
87 04339a32-44b6-4e05-be4d-a2aee0149342 "9780312421991 When her best friend Sheba Hart's love affair with an underage male student comes to light, igniting a media circus, solitary schooltea
88 0445a56e-7df2-497e-92c1-7749e17dff80 "9780140441222 Strongly influenced by Classical drama, Jean Racine (1639–99) broke away from the grandiose theatricality of baroque drama to create wo
89 044fa8ee-ddbe-43a8-a54e-237d3249fa76 "9780786849734 The Little Einsteins, equipped with their camera, go on a journey through space, exploring each of the planets, landing on Mars, and lo
90 048393a7-7793-433e-83f6-73b275e99fb4 "9780743250412 Nineteenth-century writer Henry James is heartbroken when his first play performs poorly in contrast to Oscar Wilde's The Importance of
91 0484771b-9846-4735-8492-d84742920c7b "9780553804935 In eighteenth-century England, Lia, the daughter of the leader of the drakon tribe whose members can transform from human to dragon, us
92 048e96c9-23dd-4839-bd36-2e58dc284b8e "9781590593899 * Covers three years of the best essays. * Essays range from technical to humorous, but are always tangible. * Beautifully written and
93 0492651d-a7a4-4e52-b3c8-ed8bd34d912a "9780060887964 ""My heart is afraid that it will have to suffer,"" the boy told the alchemist one night as they looked up at the moonless sky."" Tell
94 04944b77-fa84-4f62-a40d-b18cce7d513c "9780140449099 This text is a revised edition of Cervantes' classic tale. Don Quixote has become so entranced by reading romances of chivalry that he
95 049c4ce0-be7f-4a7e-9311-a4aa2ee54bd1 "9780785120193 Follows the adventures of the X-Men, who band together to fight enemies, form tentative alliances with members of Magneto's gang, and p
96 04a894e9-e8ea-48b2-8bb8-b31b628c3b1a "9780099481683 A classic tale for modern times, Skipping Christmas offers a hilarious look at the chaos and frenzy that has become part of our holiday
97 04b2f564-c512-4603-9d5b-407e933df600 "9780552152945 The tenth Discworld novel. The alchemists of the Discworld have discovered the magic of the silver screen. But what is the dark secret
98 04ce08d6-e4c8-429f-81a9-5304f2ada1f9 "9780316926607 A ""lavishly entertaining"" (Publishers Weekly) distillation of Waugh's genius--abundant evidence that one of the twentieth century's m
99 04ce8be1-2a12-4717-a70a-7991f2c5975b 9780691024714 The story of Nabokov's life continues with his arrival in the United States in 1940. He found that supporting himself and his family was
100 04de27af-e0b9-461e-9ffb-cabf784bbad8 "9780310257868 Over one million people have experienced the groundbreaking evangelism training course Becoming a Contagious Christian -- a proven reso
101 050067d9-7e51-473f-91ad-a053d2efe20c "9780684873206 Sports, politics, and sex collide in Hunter S. Thompson’s wildly popular ESPN.com columns. From the author of Fear and Loathing in Las
102 05008373-1826-46f8-b5d0-b8398d8a2ef2 "9780765341136 In a distant future where humans have journeyed throughout space and formed a ruling body called the Empire, Dr. Gretchen Andersen is c
103 051233ca-b6d6-4080-a9c4-b9226dc5e219 "9781844151455 Mansur Abdulin fought in the front ranks of the Soviet infantry against the German invaders at Stalingrad, Kursk and on the banks of th